name: build container
on: 
  # triggered by user action only
  workflow_dispatch:
    inputs:
      PG_VERSION:
        description: 'Postgres version'
        required: true
        default: '16'
      EXTENSIONS:
        description: 'Postgres extensions to install'
        required: true
        default: 'cron timescaledb pgvector h3 postgis-3 pgrouting'
      TIMESCALEDB_VERSION:
        description: 'TimescaleDB version'
        required: true
        default: '2.16.1'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      # authenticate ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: calculate image tag
      id: vars
      run: |
        echo "IMAGE_TAG=${{ github.event.inputs.PG_VERSION }}" >> $GITHUB_OUTPUT
    - id: lower-owner
      name: Repository to lowercase
      run: |
        echo "owner=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
    - uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ steps.lower-owner.outputs.owner }}:latest,ghcr.io/${{ steps.lower-owner.outputs.owner }}/postgresql:${{ steps.vars.outputs.IMAGE_TAG }}
        build-args: |
          POSTGRESQL_VERSION=${{ github.event.inputs.PG_VERSION }}
          EXTENSIONS=${{ github.event.inputs.EXTENSIONS }}
          TIMESCALEDB_VERSION=${{ github.event.inputs.TIMESCALEDB_VERSION }}
